### PR TITLE
Ability to change radio button choice with Arrow Keys

### PR DESCRIPTION
**Pull request by kyleperik**

### CODE REVIEW

**Comment by pfalcon** [comment]
Merged, thanks!

**Comment by kyleperik** [comment]
No problem, sorry it took a while, and sorry about the many pointless
commits. Still getting the hang of this. I'm happy to help with anything
else you have with this project!

**Comment by pfalcon** [comment]
No problem either, thanks for not forgetting it! Btw, seeing your code, I spotted a possibility of refactor - to reuse ItemSelWidget previously introduced in menu.py, now done in the latest commits.

**Comment by pfalcon** [comment]
As for further contribution, feel free to put picotui at work in your projects and share the feedback. One thing I'd like to do is to finalize package/module structure for 1.0, see e.g. https://github.com/pfalcon/picotui/issues/8. Comments welcome.

**Pull request closed without merging**
