### PR TITLE
Pressing Space or Enter will activate a Button press as well as clicking

### PR DESCRIPTION
**Pull request by kyleperik**
Needed this in a case where I didn't have access to the mouse.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the patch, sorry for the delay with processing it. Merged. Please consider doing a "git log" and follow existing format of commit messages (this trick works with any git project out there).

**Comment by kyleperik** [comment]
Okay, sorry about that. I'm pretty new to git/open source, so good to know.
Thanks!

**Comment by pfalcon** [comment]
Also, I had to remove activating on Space, as it doesn't work for dialog-finishing buttons (and widgets in general), as explained here: https://github.com/pfalcon/picotui/commit/a2ae9f8a496938fdc30d6f51e2ac7d5bffa1fcb3. widget_demo.py was updated to add "standalone" buttons to check their behavior.

**Comment by kyleperik** [comment]
Okay, that sounds fine. If I have time/the need I might implement pure
keyboard controls for radio buttons. Is that okay?

**Comment by pfalcon** [comment]
Sure, you're welcome. Just please be sure to check them with existing tests ("demos").

**Comment by kyleperik** [comment]
Okay, will do.

**Pull request closed without merging**
